# Generated by Django 2.1.2 on 2018-12-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='entregado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
