# Generated by Django 2.1.2 on 2018-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181204_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cintura',
            field=models.CharField(choices=[('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuello',
            field=models.CharField(choices=[('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='largo',
            field=models.CharField(choices=[('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='manga',
            field=models.CharField(choices=[('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pecho',
            field=models.CharField(choices=[('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50')], max_length=2),
        ),
    ]
