# Generated by Django 2.1.2 on 2018-12-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20181209_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='largo',
            new_name='largo_pantalon',
        ),
    ]
